name: 'enterprise_rag'
version: '1.0.0'
config-version: 2

profile: 'enterprise_rag'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  enterprise_rag:
    materialized: table 